name: Benchmark
on:
  workflow_dispatch:

jobs:
  clean-up-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        # Only cancel non-master branch runs
        if: ${{ github.ref != 'refs/heads/master' }}
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ github.token }}
  build:
    runs-on: [self-hosted]
    needs: clean-up-actions
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly-2022-08-05
          components: rustfmt
          target: wasm32-unknown-unknown
          default: true
      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v1.12
      - name: Run benchmark
        run: |
          cargo run \
            --profile production \
            --bin=acala \
            --features=runtime-benchmarks \
            --features=with-acala-runtime \
            --features=on-chain-release-build \
            -- benchmark pallet \
            --chain=acala-dev \
            --steps=50 --repeat=20 \
            --pallet="${PALLET:=*}" \
            --extrinsic="${EXTRINSIC:=*}" \
            --execution=wasm --wasm-execution=compiled \
            --heap-pages=4096 \
            --template=./templates/runtime-weight-template.hbs \
            --output=./runtime/acala/src/weights/ > output.txt

      - name: Save output as artifact
        uses: actions/upload-artifact@v2
        with:
          name: Benchmark result
          path: |
            output.txt
